version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  ignore:
  - dependency-name: django
    versions:
    - ">=3.3"
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  ignore:
  - dependency-name: python
    versions:
    - ">=3.9"
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/ember"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  versioning-strategy: increase
  commit-message:
    prefix: chore
    include: scope
  ignore:
    # mirror https://github.com/projectcaluma/ember-caluma/blob/main/.github/dependabot.yml
    - dependency-name: graphql
      versions:
        - ">= 16"
    # We're not ready yet
    - dependency-name: ember-source
      versions:
        - ">= 4"
    - dependency-name: ember-cli
      versions:
        - ">= 4"
    - dependency-name: ember-data
      versions:
        - ">= 4"
    # https://github.com/ember-cli/ember-cli/issues/9307
    - dependency-name: eslint
      versions:
        - ">= 8"
