version: 2
updates:
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - ">=3"
  - dependency-name: requests-mock
    versions:
    - 1.9.0
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: flake8
    versions:
    - 3.9.0
    - 3.9.1
  - dependency-name: pytest-randomly
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: pre-commit
    versions:
    - 2.10.1
    - 2.11.0
    - 2.12.0
  - dependency-name: django
    versions:
    - 2.2.20
  - dependency-name: django-extensions
    versions:
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: pytest
    versions:
    - 6.2.3
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
    - 3.12.4
  - dependency-name: django-localized-fields
    versions:
    - "6.3"
    - "6.4"
  - dependency-name: isort
    versions:
    - 5.8.0
  - dependency-name: flake8-docstrings
    versions:
    - 1.6.0
  - dependency-name: drf-extra-fields
    versions:
    - 3.1.0
    - 3.1.1
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/api"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - ">=3.9"
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/ember"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
  - dependency-name: ember-data
    versions:
    - 3.25.0
  - dependency-name: ember-caluma
    versions:
    - 6.10.2
    - 6.9.2
    - 6.9.3
    - 7.0.2
    - 7.0.3
  - dependency-name: ember-apollo-client
    versions:
    - 3.0.2
    - 3.0.3
    - 3.1.0
  - dependency-name: ember-cli-app-version
    versions:
    - 4.0.0
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
