---
x-version: 0.7.0

services:
  db:
    image: postgres:14-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"

  api:
    image: ghcr.io/adfinis/mysagw/api:0.3.2
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  caluma:
    image: ghcr.io/adfinis/mysagw/caluma:0.3.8
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=60
      - OIDC_GROUPS_CLAIM=mysagw_groups
      - EVENT_RECEIVER_MODULES=caluma.extensions.events
      - VISIBILITY_CLASSES=caluma.caluma_user.visibilities.Authenticated,caluma.extensions.visibilities.MySAGWVisibility
      - PERMISSION_CLASSES=caluma.caluma_user.permissions.IsAuthenticated,caluma.extensions.permissions.MySAGWPermission
      - DYNAMIC_TASKS_CLASSES=caluma.extensions.dynamic_tasks.CustomDynamicTasks
      - VALIDATION_CLASSES=caluma.extensions.validations.CustomValidation
      - META_FIELDS=assigneeEmail,assigneeName
      - ENABLE_HEALTHZ_ENDPOINT=true
    depends_on:
      - db
      - keycloak

  caddy:
    image: caddy:2.6-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  keycloak:
    depends_on:
      - db
    image: quay.io/keycloak/keycloak:26.2.2
    volumes:
      - ./keycloak/config.json:/opt/keycloak/data/import/test-config.json
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db/keycloak
      - KC_DB_USERNAME=keycloak
      - KEYCLOAK_ADMIN=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded
    command: start

  ember:
    image: ghcr.io/adfinis/mysagw/ember:0.4.0

  minio:
    image: minio/minio:RELEASE.2024-12-13T22-19-12Z
    volumes:
      - minio_data_snsd:/data
    command: server data

  mc:
    image: minio/mc:latest
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      mc config host add dc-minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} --api S3v4;
      mc mb dc-minio/caluma-media;
      true"
    depends_on:
      - minio

  dms:
    image: ghcr.io/adfinis/document-merge-service:6.6.1
    depends_on:
      - db
    volumes:
      - templatefiles:/var/lib/document-merge-service/media
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=dms
      - DATABASE_USER=dms
      - ALLOWED_HOSTS=dms
      - OIDC_BEARER_TOKEN_REVALIDATION_TIME=60
      # needed until https://github.com/adfinis-sygroup/document-merge-service/issues/407 is closed
      - DOCXTEMPLATE_JINJA_EXTENSIONS=

volumes:
  dbdata:
  caddy_data:
  caddy_config:
  minio_data_snsd:
  templatefiles:
