---
services:
  db:
    env_file: ./.envs/.staging/.postgres
    restart: unless-stopped

  api:
    image: ghcr.io/adfinis/mysagw:0.1.0
    env_file: ./.envs/.staging/.api
    restart: unless-stopped

  caluma:
    env_file: ./.envs/.staging/.caluma
    restart: unless-stopped

  caddy:
    env_file: ./.envs/.staging/.caddy
    restart: unless-stopped

  keycloak:
    env_file: ./.envs/.staging/.keycloak
    restart: unless-stopped

  ember:
    build:
      args:
        OIDC_HOST: "${OIDC_HOST:?Set OIDC_HOST env variable}"
    restart: unless-stopped

  minio:
    env_file: ./.envs/.staging/.minio
    restart: unless-stopped

  mc:
    env_file: ./.envs/.staging/.minio

  dms:
    env_file: ./.envs/.staging/.dms
    restart: unless-stopped
