---
services:
  db:
    env_file: ./.envs/.local/.postgres

  api:
    build:
      context: ./api/
      target: dev
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./api:/app
      - ./api/caluma_extensions:/app/caluma/extensions
      - ./api/data:/app/caluma/data:ro
      - ./api/.env:/app/.env
    ports:
      - "8000:8000"
    env_file: ./.envs/.local/.api

  caddy:
    env_file: ./.envs/.local/.caddy
    environment:
      - GRAPHIQL_PROXY=reverse_proxy /static/graphene_django/* http://api:8000
    networks:
      default:
        aliases:
          - mysagw.localhost

  keycloak:
    env_file: ./.envs/.local/.keycloak
    command: start-dev

  ember:
    build: ./ember

  mail:
    image: axllent/mailpit:v1.28
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    ports:
      - "8025:8025"

  minio:
    env_file: ./.envs/.local/.minio
    ports:
      - "9001:9001"

  mc:
    env_file: ./.envs/.local/.minio

  dms:
    env_file: ./.envs/.local/.dms
# Suddenly with this, the uwsgi workers are constantly restarted. Uncommenting for now.
#    deploy:
#      resources:
#        limits:
#          memory: 1024M
