---
services:
  db:
    env_file: ./.envs/.production/.postgres
    restart: unless-stopped

  api:
    env_file: ./.envs/.production/.api
    restart: unless-stopped

  caluma:
    env_file: ./.envs/.production/.caluma
    restart: unless-stopped

  caddy:
    env_file: ./.envs/.production/.caddy
    restart: unless-stopped

  keycloak:
    env_file: ./.envs/.production/.keycloak
    restart: unless-stopped

  ember:
    restart: unless-stopped

  minio:
    env_file: ./.envs/.production/.minio
    restart: unless-stopped

  mc:
    env_file: ./.envs/.production/.minio

  dms:
    env_file: ./.envs/.production/.dms
    restart: unless-stopped
