# Generated by Django 3.2.14 on 2022-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalsnippet",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical snippet",
                "verbose_name_plural": "historical snippets",
            },
        ),
        migrations.AlterField(
            model_name="historicalsnippet",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
