# Generated by Django 3.2.23 on 2023-11-06 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_simple_history_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snippet",
            options={"ordering": ("title",)},
        ),
    ]
