# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots["test_identity_export[admin] 1"] = [
    [
        "first_name",
        "last_name",
        "localized_salutation",
        "language",
        "is_organisation",
        "organisation_name",
        "email",
        "additional_emails",
        "phone_numbers",
        "address_addition_1",
        "address_addition_2",
        "address_addition_3",
        "street_and_number",
        "po_box",
        "postcode",
        "town",
        "country",
    ],
    [
        "Caitlin",
        "Adams",
        "",
        "de",
        0,
        "",
        "ryanjohnson@example.net",
        """portertodd@example.com
sharonjohnson@example.org
suzanne77@example.net""",
        """+41774226576
+41311370448
+41772344015""",
        "",
        "",
        "",
        "7562 Navarro Summit Suite 837",
        "",
        "54786",
        "Tiffanyside",
        "Andorra",
    ],
    [
        "Craig",
        "Brady",
        "Monsieur",
        "fr",
        0,
        "",
        "qskinner@example.com",
        """joshua61@example.com
rebecca04@example.com
wyatttroy@example.com""",
        """+41569351062
+41318120675
+41786259851""",
        "",
        "",
        "",
        "73129 Autumn Roads",
        "",
        "69035",
        "Karamouth",
        "Dominica",
    ],
    [
        "Christopher",
        "Brown",
        "Mrs.",
        "en",
        0,
        "",
        "jackellis@example.com",
        """baileypatrick@example.com
mercedes89@example.net
reynoldsjulie@example.org""",
        """+41776065100
+41310479220
+41567507090""",
        "",
        "",
        "",
        "28121 Davis Prairie",
        "",
        "07262",
        "Tranmouth",
        "Kasachstan",
    ],
    [
        "Samantha",
        "Brown",
        "",
        "de",
        0,
        "",
        "carlcunningham@example.net",
        """christinegibson@example.net
danielle56@example.net
edward48@example.org""",
        """+41782059514
+41416323667
+41773010584""",
        "",
        "",
        "",
        "2566 Rebecca Valleys",
        "",
        "97864",
        "Lake Michael",
        "Griechenland",
    ],
    [
        "Elizabeth",
        "Collins",
        "",
        "de",
        0,
        "",
        "bryantjessica@example.com",
        """brittneylee@example.com
chavezdennis@example.org
halldeborah@example.org""",
        """+41766950410
+41417907749
+41787652764""",
        "",
        "",
        "",
        "03960 Zachary Bypass",
        "",
        "15927",
        "Hansonfurt",
        "Brunei",
    ],
    [
        "Cameron",
        "Howard",
        "",
        "de",
        0,
        "",
        "calebsoto@example.net",
        """lmurphy@example.com
mirandadavis@example.com
toddstevenson@example.org""",
        """+41785402337
+41442180721
+41563077386""",
        "",
        "",
        "",
        "90372 Gail Mountains Apt. 362",
        "",
        "70514",
        "Laurenton",
        "Malaysia",
    ],
    [
        "Jared",
        "Hunter",
        "",
        "de",
        0,
        "",
        "jenniferwilliams@example.org",
        """kdalton@example.com
tlandry@example.net
wilkinsonkatherine@example.org""",
        """+41562214464
+41780229422
+41797382877""",
        "",
        "",
        "",
        "590 Rosales Grove",
        "",
        "82820",
        "East Mandy",
        "Simbabwe",
    ],
    [
        "Carolyn",
        "Stephens",
        "",
        "de",
        0,
        "",
        "khayes@example.org",
        """crystal26@example.com
ptaylor@example.org
vwilson@example.org""",
        """+41318455609
+41418236559
+41798217489""",
        "",
        "",
        "",
        "7430 Padilla Radial Suite 023",
        "",
        "54372",
        "South Drewstad",
        "Indonesien",
    ],
    [
        "Cynthia",
        "Ware",
        "",
        "de",
        0,
        "",
        "jonathan94@example.org",
        """millerkeith@example.com
robert91@example.net
westandre@example.com""",
        """+41769539902
+41441271026
+41789413998""",
        "",
        "",
        "",
        "61956 Austin Highway",
        "",
        "00749",
        "New Victoriahaven",
        "Panama",
    ],
    [
        "Hector",
        "Wilson",
        "",
        "de",
        1,
        "Bryan and Sons",
        "lhernandez@example.net",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    [
        "Thomas",
        "Woods",
        "",
        "de",
        0,
        "",
        "tanya60@example.net",
        """hendersonjill@example.org
moorejason@example.net
xgonzales@example.com""",
        """+41561319205
+41443782740
+41779627131""",
        "",
        "",
        "",
        "49184 Scott Forge Apt. 631",
        "",
        "52437",
        "Lake Sherri",
        "Pakistan",
    ],
]

snapshots["test_identity_export_labels_context[admin] 1"] = [
    [
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Dominica",
            "first_name": "Caitlin",
            "last_name": "Adams",
            "organisation_name": "",
            "po_box": "",
            "postcode": "69035",
            "street_and_number": "3129 Autumn Roads",
            "town": "Karamouth",
        },
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Jemen",
            "first_name": "Craig",
            "last_name": "Brady",
            "organisation_name": "",
            "po_box": "",
            "postcode": "71090",
            "street_and_number": "2327 Hayley Bridge",
            "town": "Cruzberg",
        },
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Türkei",
            "first_name": "Christopher",
            "last_name": "Brown",
            "organisation_name": "",
            "po_box": "",
            "postcode": "99599",
            "street_and_number": "26576 Nixon Mountain Suite 202",
            "town": "Port Bonnie",
        },
    ],
    [
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Belize",
            "first_name": "Samantha",
            "last_name": "Brown",
            "organisation_name": "",
            "po_box": "",
            "postcode": "87711",
            "street_and_number": "00390 Massey Center",
            "town": "Michaelland",
        },
        {
            "address_addition_1": "Haus der Akademien",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Vatikanstadt",
            "first_name": "Elizabeth",
            "last_name": "Collins",
            "organisation_name": "SAGW",
            "po_box": "23",
            "postcode": "36813",
            "street_and_number": "762 Mark Turnpike Apt. 828",
            "town": "West Ronald",
        },
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Schweiz",
            "first_name": "Cameron",
            "last_name": "Howard",
            "organisation_name": "",
            "po_box": "",
            "postcode": "56598",
            "street_and_number": "0356 Arroyo Isle Suite 694",
            "town": "North Sandraville",
        },
    ],
    [
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Papua Neu Guinea",
            "first_name": "Jared",
            "last_name": "Hunter",
            "organisation_name": "",
            "po_box": "",
            "postcode": "66800",
            "street_and_number": "70906 Ryan Crossing Apt. 052",
            "town": "West Darylfort",
        },
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Ruanda",
            "first_name": "Carolyn",
            "last_name": "Stephens",
            "organisation_name": "",
            "po_box": "",
            "postcode": "42361",
            "street_and_number": "589 Patricia Club",
            "town": "New Dale",
        },
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Polen",
            "first_name": "Cynthia",
            "last_name": "Ware",
            "organisation_name": "",
            "po_box": "",
            "postcode": "19068",
            "street_and_number": "5242 Hardy Crescent Apt. 558",
            "town": "Fergusonfurt",
        },
    ],
    [
        {
            "address_addition_1": "",
            "address_addition_2": "",
            "address_addition_3": "",
            "country": "Irak",
            "first_name": "Thomas",
            "last_name": "Woods",
            "organisation_name": "",
            "po_box": "",
            "postcode": "35443",
            "street_and_number": "99841 Quinn Common",
            "town": "Brownton",
        }
    ],
]
