# Generated by Django 2.2.19 on 2021-03-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalidentity",
            name="language",
            field=models.CharField(
                choices=[("de", "German"), ("en", "English"), ("fr", "French")],
                default="de",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="historicalidentity",
            name="salutation",
            field=models.CharField(
                choices=[
                    ("male", {"de": "Herr", "en": "Mr.", "fr": "Monsieur"}),
                    ("female", {"de": "Frau", "en": "Mrs.", "fr": "Madame"}),
                    ("neutral", {"de": "", "en": "", "fr": ""}),
                ],
                default="neutral",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="language",
            field=models.CharField(
                choices=[("de", "German"), ("en", "English"), ("fr", "French")],
                default="de",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="salutation",
            field=models.CharField(
                choices=[
                    ("male", {"de": "Herr", "en": "Mr.", "fr": "Monsieur"}),
                    ("female", {"de": "Frau", "en": "Mrs.", "fr": "Madame"}),
                    ("neutral", {"de": "", "en": "", "fr": ""}),
                ],
                default="neutral",
                max_length=7,
            ),
        ),
    ]
