# Generated by Django 2.2.19 on 2021-03-26 10:01

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localized_fields.fields.char_field
import mysagw.models
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_salutation_and_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAddress",
            fields=[
                ("history_user_id", models.CharField(max_length=150, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "address_addition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("street_and_number", models.CharField(max_length=255)),
                ("po_box", models.CharField(blank=True, max_length=255, null=True)),
                ("postcode", models.CharField(max_length=255)),
                ("town", models.CharField(max_length=255)),
                (
                    "country",
                    django_countries.fields.CountryField(default="CH", max_length=2),
                ),
                (
                    "description",
                    localized_fields.fields.char_field.LocalizedCharField(
                        blank=True, null=True, required=[]
                    ),
                ),
                ("default", mysagw.models.UniqueBooleanField(default=False)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="identity.Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical address",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address_addition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("street_and_number", models.CharField(max_length=255)),
                ("po_box", models.CharField(blank=True, max_length=255, null=True)),
                ("postcode", models.CharField(max_length=255)),
                ("town", models.CharField(max_length=255)),
                (
                    "country",
                    django_countries.fields.CountryField(default="CH", max_length=2),
                ),
                (
                    "description",
                    localized_fields.fields.char_field.LocalizedCharField(
                        blank=True, null=True, required=[]
                    ),
                ),
                ("default", mysagw.models.UniqueBooleanField(default=False)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="identity.Identity",
                    ),
                ),
            ],
            options={
                "ordering": ("-default",),
            },
        ),
    ]
