# Generated by Django 2.2.19 on 2021-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_address_historicaladdress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalidentity",
            name="salutation",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("neutral", "neutral"),
                ],
                default="neutral",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="salutation",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("neutral", "neutral"),
                ],
                default="neutral",
                max_length=7,
            ),
        ),
    ]
