# Generated by Django 2.2.20 on 2021-08-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_email_and_phone_ordering"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="address_addition",
            new_name="address_addition_1",
        ),
        migrations.RenameField(
            model_name="historicaladdress",
            old_name="address_addition",
            new_name="address_addition_1",
        ),
        migrations.AddField(
            model_name="address",
            name="address_addition_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="address_addition_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="address_addition_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="address_addition_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
