# Generated by Django 2.2.20 on 2021-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_address_addition"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalidentity",
            name="is_advisory_board",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalidentity",
            name="is_expert_association",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="identity",
            name="is_advisory_board",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="identity",
            name="is_expert_association",
            field=models.BooleanField(default=False),
        ),
    ]
