# Generated by Django 2.2.20 on 2021-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0008_public_localized_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalidentity",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
