# Generated by Django 3.2.9 on 2022-02-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0009_identity_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalidentity",
            name="title",
            field=models.CharField(
                choices=[
                    ("dr", "dr"),
                    ("prof", "prof"),
                    ("prof-dr", "prof-dr"),
                    ("pd-dr", "pd-dr"),
                    ("none", "none"),
                ],
                default="none",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="title",
            field=models.CharField(
                choices=[
                    ("dr", "dr"),
                    ("prof", "prof"),
                    ("prof-dr", "prof-dr"),
                    ("pd-dr", "pd-dr"),
                    ("none", "none"),
                ],
                default="none",
                max_length=9,
            ),
        ),
    ]
