# Generated by Django 3.2.16 on 2023-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0011_simple_history_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershiprole",
            options={"ordering": ["-sort", "title"]},
        ),
        migrations.AddField(
            model_name="historicalmembershiprole",
            name="sort",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name="membershiprole",
            name="sort",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
