# Generated by Django 5.2.8 on 2025-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_add_sort_to_membershipsrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidentity',
            name='title',
            field=models.CharField(choices=[('dr', 'dr'), ('prof', 'prof'), ('prof-dr', 'prof-dr'), ('prof-em-dr', 'prof-em-dr'), ('pd-dr', 'pd-dr'), ('none', 'none')], default='none', max_length=14),
        ),
        migrations.AlterField(
            model_name='identity',
            name='title',
            field=models.CharField(choices=[('dr', 'dr'), ('prof', 'prof'), ('prof-dr', 'prof-dr'), ('prof-em-dr', 'prof-em-dr'), ('pd-dr', 'pd-dr'), ('none', 'none')], default='none', max_length=14),
        ),
    ]
