# Generated by Django 5.2.8 on 2026-01-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_alter_historicalidentity_title_alter_identity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidentity',
            name='organisation_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='organisation_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
