query Receipts($case_id: ID!) {
  node(id: $case_id) {
    ... on Case {
      document {
        form {
          name
        }
      }
      additionalData: workItems(filter: [{task: "additional-data-form"}], first: 1) {
        edges {
          node {
            document {
              quittungen: answers(filter: [{question: "additional-data-quittungen"}]) {
                edges {
                  node {
                    ... on TableAnswer {
                      value {
                        answers(filter: [{question: "additional-data-row-quittung"}]) {
                          edges {
                            node {
                              ... on FilesAnswer {
                                value {
                                  downloadUrl
                                  metadata
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
              applicant_name: answers(filter: [{question: "additional-data-name"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              applicant_address: answers(filter: [{question: "additional-data-adresse"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              applicant_postcode: answers(filter: [{question: "additional-data-postleitzahl"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              applicant_city: answers(filter: [{question: "additional-data-ort"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              applicant_land: answers(filter: [{question: "additional-data-land"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              zahlungszweck: answers(filter: [{question: "additional-data-zahlungszweck"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              iban: answers(filter: [{question: "additional-data-iban"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              bank: answers(filter: [{question: "additional-data-bank"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
              bank_town: answers(filter: [{question: "additional-data-bank-town"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
      main: document {
        dossierno: answers(filter: [{question: "dossier-nr"}]) {
          edges {
            node {
              ... on StringAnswer {
                value
              }
            }
          }
        }
        sektion: answers(filter: [{question: "sektion"}]) {
          edges {
            node {
              ... on StringAnswer {
                value
              }
            }
          }
        }
        vp_year: answers(filter: [{question: "verteilplan-nr"}]) {
          edges {
            node {
              ... on StringAnswer {
                value
              }
            }
          }
        }
        mitgliedinstitution: answers(filter: [{question: "mitgliedinstitution"}]) {
          edges {
            node {
              ... on StringAnswer {
                value
                question {
                  ... on ChoiceQuestion {
                    options {
                      edges {
                        node {
                          slug
                          label
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      defineAmount: workItems(filter: [{task: "define-amount"}], order: [{attribute: CREATED_AT, direction: DESC}], first: 1) {
        edges {
          node {
            document {
              total: answers(filter: [{question: "define-amount-amount-float"}]) {
                edges {
                  node {
                    ... on FloatAnswer {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
      decisionCredit: workItems(filter: [{task: "decision-and-credit"}], order: [{attribute: CREATED_AT, direction: DESC}], first: 1) {
        edges {
          node {
            document {
              circKontonummer: answers(filter: [{question: "circ-kontonummer"}]) {
                edges {
                  node {
                    ... on StringAnswer {
                      value
                      question {
                        ... on ChoiceQuestion {
                          options {
                            edges {
                              node {
                                slug
                                label
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      advanceCredits: workItems(filter: [{task: "advance-credits"}], order: [{attribute: CREATED_AT, direction: DESC}], first: 1) {
        edges {
          node {
            document {
              vorschussbetrag: answers(filter: [{question: "advance-credit-amount-float"}]) {
                edges {
                  node {
                    ... on FloatAnswer {
                      value
                    }
                  }
                }
              }
              vorschussdatum: answers(filter: [{question: "advance-credit-date"}]) {
                edges {
                  node {
                    ... on DateAnswer {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
